<?xml version="1.0" ?>

<robot name="cable_joint" xmlns:xacro="https://www.ros.org/wiki/xacro" >

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="EPSILON" value="1e-8"/>
    <!-- properties of link_base -->
    <xacro:property name="R_BASE" value="0.1"/>
    <xacro:property name="L_BASE" value="0.02"/>
    <xacro:property name="M_BASE" value="10"/>
    <!-- properties of link_camera_body -->
    <xacro:property name="L_CAMBODY" value="0.02"/>
    <xacro:property name="M_CAMBODY" value="0.1"/>
    <!-- properties of link_lens_body -->
    <xacro:property name="R_LENS" value="0.02"/>
    <xacro:property name="L_LENS" value="0.002"/>
    <xacro:property name="M_LENS" value="0.01"/>
    <!-- properties of link_pin's -->
    <xacro:property name="R_PIN" value="0.02"/>
    <xacro:property name="M_PIN" value="1"/>
    <!-- properties of link_lowerSupport -->
    <xacro:property name="R_LOWSUPPORT" value="0.015"/>
    <xacro:property name="L_LOWSUPPORT" value="0.14"/>
    <xacro:property name="M_LOWSUPPORT" value="1"/>
    <!-- properties of link_hiddenLink -->
    <xacro:property name="R_HIDLINK" value="0.000001"/>
    <xacro:property name="L_HIDLINK" value="0.000004"/>
    <xacro:property name="M_HIDLINK" value="0.00001"/>
    <!-- properties of link_ball -->
    <xacro:property name="R_BALL" value="0.04"/>
    <xacro:property name="M_BALL" value="1"/>
    <!-- properties of link_upperSupport -->
    <xacro:property name="R_UPPSUPPORT" value="0.01"/>
    <xacro:property name="L_UPPSUPPORT" value="0.08"/>
    <xacro:property name="M_UPPSUPPORT" value="0.1"/>
    <!-- properties of link_disc -->
    <xacro:property name="R_DISC" value="0.1"/>
    <xacro:property name="L_DISC" value="0.02"/>
    <xacro:property name="M_DISC" value="0.1"/>
    <!-- properties of link_cube's -->
    <xacro:property name="L_CUBE" value="0.02"/>
    <xacro:property name="M_CUBE" value="0.001"/>


    <!-- Import all Gazebo-customization elements, including Gazebo colors -->
    <xacro:include filename="$(find cable_joint_description)/urdf/cable_joint.gazebo.xacro" />
    <!-- Import Rviz colors -->
    <xacro:include filename="$(find cable_joint_description)/urdf/materials.xacro" />

    <!-- Used for fixing robot to Gazebo 'base_link' -->
    <link name="world"/>

    <joint name="joint_world_base" type="fixed">
        <parent link="world"/>
        <child link="link_base"/>
    </joint>

    <link name="link_base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_BASE}" radius="${R_BASE}"/>
            </geometry>
        <material name="black"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_BASE}" radius="${R_BASE}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1000"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_BASE*(3*R_BASE*R_BASE+L_BASE*L_BASE)}" ixy="0" ixz="0" iyy="${1/12*M_BASE*(3*R_BASE*R_BASE+L_BASE*L_BASE)}" iyz="0" izz="${1/2*M_BASE*R_BASE*R_BASE}"/>
        </inertial>
    </link>

    <joint name="joint_world_soucambody" type="revolute">
        <origin rpy="0 0 ${PI/2}" xyz="0 -0.5 ${L_CAMBODY/2}"/>
        <parent link="world"/>
        <child link="link_southCameraBody"/>
        <limit effort="0" lower="0" upper="0" velocity="0"/>
        <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint>

    <link name="link_southCameraBody">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${L_CAMBODY} ${L_CAMBODY*2} ${L_CAMBODY*2}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${L_CAMBODY} ${L_CAMBODY*2} ${L_CAMBODY*2}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_CAMBODY}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_CAMBODY*(L_CAMBODY*L_CAMBODY*4+L_CAMBODY*L_CAMBODY*4)}" ixy="0" ixz="0" iyy="${1/12*M_CAMBODY*(L_CAMBODY*L_CAMBODY+L_CAMBODY*L_CAMBODY*4)}" iyz="0" izz="${1/12*M_CAMBODY*(L_CAMBODY*L_CAMBODY*4+L_CAMBODY*L_CAMBODY)}"/>
        </inertial>
    </link>

    <joint name="joint_soucambody_soulens" type="revolute">
        <origin rpy="0 ${PI/2} 0" xyz="${L_CAMBODY/2+L_LENS/2} 0 0"/>
        <parent link="link_southCameraBody"/>
        <child link="link_southLens"/>
        <limit effort="0" lower="0" upper="0" velocity="0"/>
        <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint>

    <link name="link_southLens">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_LENS}" radius="${R_LENS}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_LENS}" radius="${R_LENS}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_LENS}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_LENS*(3*R_LENS*R_LENS+L_LENS*L_LENS)}" ixy="0" ixz="0" iyy="${1/12*M_LENS*(3*R_LENS*R_LENS+L_LENS*L_LENS)}" iyz="0" izz="${1/2*M_LENS*R_LENS*R_LENS}"/>
        </inertial>
    </link>
    <!-- rotate optical link, x axis should be pointing to the view-->
    <joint name="joint_soulens_souopt" type="fixed">
      <origin xyz="0 0 0" rpy="${-PI/2} ${-PI/2} ${PI/2}"/>
      <parent link="link_southLens"/>
      <child link="link_southOptical"/>
    </joint>
    <link name="link_southOptical">
    </link>

    <joint name="joint_base_eastpin" type="revolute">
        <parent link="link_base"/>
        <child link="link_eastPin"/>
        <origin rpy="0 0 0" xyz="${R_BASE} 0 ${L_BASE/2}"/>
        <limit effort="0" lower="0" upper="0" velocity="0"/>
        <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint>

    <link name="link_eastPin">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${R_PIN}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${R_PIN}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_PIN}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${2/5*M_PIN*R_PIN*R_PIN}" ixy="0" ixz="0" iyy="${2/5*M_PIN*R_PIN*R_PIN}" iyz="0" izz="${2/5*M_PIN*R_PIN*R_PIN}"/>
        </inertial>
    </link>

    <joint name="joint_base_westpin" type="revolute">
        <parent link="link_base"/>
        <child link="link_westPin"/>
        <origin rpy="0 0 0" xyz="${-R_BASE} 0 ${L_BASE/2}"/>
        <limit effort="0" lower="0" upper="0" velocity="0"/>
        <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint>

    <link name="link_westPin">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${R_PIN}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${R_PIN}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_PIN}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${2/5*M_PIN*R_PIN*R_PIN}" ixy="0" ixz="0" iyy="${2/5*M_PIN*R_PIN*R_PIN}" iyz="0" izz="${2/5*M_PIN*R_PIN*R_PIN}"/>
        </inertial>
    </link>

    <joint name="joint_base_lowersupport" type="revolute">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <limit effort="0" lower="0" upper="0" velocity="0"/>
        <axis rpy="0 0 0" xyz="0 0 1"/>
        <parent link="link_base"/>
        <child link="link_lowerSupport"/>
        <origin rpy="0 0 0" xyz="0 0 0.01"/>
    </joint>

    <link name="link_lowerSupport">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.07"/>
            <geometry>
                <cylinder length="${L_LOWSUPPORT}" radius="${R_LOWSUPPORT}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.07"/>
            <geometry>
                <cylinder length="${L_LOWSUPPORT}" radius="${R_LOWSUPPORT}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_LOWSUPPORT}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_LOWSUPPORT*(3*R_LOWSUPPORT*R_LOWSUPPORT+L_LOWSUPPORT*L_LOWSUPPORT)}" ixy="0" ixz="0" iyy="${1/12*M_LOWSUPPORT*(3*R_LOWSUPPORT*R_LOWSUPPORT+L_LOWSUPPORT*L_LOWSUPPORT)}" iyz="0" izz="${1/2*M_LOWSUPPORT*R_LOWSUPPORT*R_LOWSUPPORT}"/>
        </inertial>
    </link>

    <joint name="joint_lowersupport_hiddenlinkroll" type="revolute">
        <parent link="link_lowerSupport"/>
        <child link="link_hiddenLinkRoll"/>
        <origin rpy="0 0 0" xyz="0 0 ${L_LOWSUPPORT}"/>
        <axis xyz="1 0 0"/>
        <limit effort="10" velocity="${PI*2}" lower="${-PI+EPSILON}" upper="${PI-EPSILON}"/>
    </joint>

    <link name="link_hiddenLinkRoll">
        <visual>
            <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_HIDLINK}" radius="${R_HIDLINK}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_HIDLINK}" radius="${R_HIDLINK}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_HIDLINK}"/>
            <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_HIDLINK*(3*R_HIDLINK*R_HIDLINK+L_HIDLINK*L_HIDLINK)}" ixy="0" ixz="0" iyy="${1/12*M_HIDLINK*(3*R_HIDLINK*R_HIDLINK+L_HIDLINK*L_HIDLINK)}" iyz="0" izz="${1/2*M_HIDLINK*R_HIDLINK*R_HIDLINK}"/>
        </inertial>
    </link>

    <joint name="joint_hiddenlinkroll_hiddenlinkpitch" type="revolute">
        <parent link="link_hiddenLinkRoll"/>
        <child link="link_hiddenLinkPitch"/>
        <origin rpy="0 0 0" xyz="0 0 ${R_HIDLINK}"/>
        <axis xyz="0 1 0"/>
        <limit effort="10" velocity="${PI*2}" lower="${-PI+EPSILON}" upper="${PI-EPSILON}"/>
    </joint>

    <link name="link_hiddenLinkPitch">
        <visual>
            <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_HIDLINK}" radius="${R_HIDLINK}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_HIDLINK}" radius="${R_HIDLINK}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_HIDLINK}"/>
            <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_HIDLINK*(3*R_HIDLINK*R_HIDLINK+L_HIDLINK*L_HIDLINK)}" ixy="0" ixz="0" iyy="${1/12*M_HIDLINK*(3*R_HIDLINK*R_HIDLINK+L_HIDLINK*L_HIDLINK)}" iyz="0" izz="${1/2*M_HIDLINK*R_HIDLINK*R_HIDLINK}"/>
        </inertial>
    </link>

    <joint name="joint_hiddenlinkpitch_ball" type="revolute">
        <parent link="link_hiddenLinkPitch"/>
        <child link="link_ball"/>
        <origin rpy="0 0 0" xyz="0 0 ${R_HIDLINK}"/>
        <axis xyz="0 0 1"/>
        <limit effort="10" velocity="${PI*2}" lower="${-PI+EPSILON}" upper="${PI-EPSILON}"/>
    </joint>

    <link name="link_ball">
        <visual>
            <origin rpy="0 0 ${PI/2}" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${R_BALL}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin rpy="0 0 ${PI/2}" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${R_BALL}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_BALL}"/>
            <origin rpy="0 0 ${PI/2}" xyz="0 0 0"/>
            <inertia ixx="${2/5*M_BALL*R_BALL*R_BALL}" ixy="0" ixz="0" iyy="${2/5*M_BALL*R_BALL*R_BALL}" iyz="0" izz="${2/5*M_BALL*R_BALL*R_BALL}"/>
        </inertial>
    </link>

    <joint name="joint_ball_uppersupport" type="revolute">
          <origin rpy="0 0 0" xyz="0 0 ${R_BALL}"/>
          <limit effort="0" lower="0" upper="0" velocity="0"/>
          <axis xyz="0 0 1"/>
          <parent link="link_ball"/>
          <child link="link_upperSupport"/>
    </joint>

    <link name="link_upperSupport">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_UPPSUPPORT}" radius="${R_UPPSUPPORT}"/>
            </geometry>
            <material name="grey"/>
        </visual>
    <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${L_UPPSUPPORT}" radius="${R_UPPSUPPORT}"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="${M_UPPSUPPORT}"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <inertia ixx="${1/12*M_UPPSUPPORT*(3*R_UPPSUPPORT*R_UPPSUPPORT+L_UPPSUPPORT*L_UPPSUPPORT)}" ixy="0" ixz="0" iyy="${1/12*M_UPPSUPPORT*(3*R_UPPSUPPORT*R_UPPSUPPORT+L_UPPSUPPORT*L_UPPSUPPORT)}" iyz="0" izz="${1/2*M_UPPSUPPORT*R_UPPSUPPORT*R_UPPSUPPORT}"/>
      </inertial>
    </link>

    <joint name="joint_uppersupport_disc" type="revolute">
          <origin rpy="0 0 0" xyz="0 0 ${L_UPPSUPPORT/2}"/>
          <limit effort="0" lower="0" upper="0" velocity="0"/>
          <axis xyz="0 0 1"/>
          <parent link="link_upperSupport"/>
          <child link="link_disc"/>
    </joint>

    <link name="link_disc">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_DISC}" radius="${R_DISC}"/>
              </geometry>
              <material name="white"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_DISC}" radius="${R_DISC}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_DISC}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_DISC*(3*R_DISC*R_DISC+L_DISC*L_DISC)}" ixy="0" ixz="0" iyy="${1/12*M_DISC*(3*R_DISC*R_DISC+L_DISC*L_DISC)}" iyz="0" izz="${1/2*M_DISC*R_DISC*R_DISC}"/>
        </inertial>
    </link>

    <joint name="joint_disc_necube" type="revolute">
          <parent link="link_disc"/>
          <child link="link_northeastCube"/>
          <origin rpy="0 0 0" xyz="0.0707 0.0707 0"/>
          <limit effort="0" lower="0" upper="0" velocity="0"/>
          <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint>

    <link name="link_northeastCube">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${L_CUBE} ${L_CUBE} ${L_CUBE}" />
            </geometry>
            <material name="purple"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${L_CUBE} ${L_CUBE} ${L_CUBE}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_CUBE}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}" ixy="0" ixz="0" iyy="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}" iyz="0" izz="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}"/>
      </inertial>
    </link>

    <joint name="joint_disc_nwcube" type="revolute">
          <parent link="link_disc"/>
          <child link="link_northwestCube"/>
          <origin rpy="0 0 0" xyz="-0.0707 0.0707 0"/>
          <limit effort="0" lower="0" upper="0" velocity="0"/>
          <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint>

    <link name="link_northwestCube">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${L_CUBE} ${L_CUBE} ${L_CUBE}" />
            </geometry>
            <material name="seance"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${L_CUBE} ${L_CUBE} ${L_CUBE}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_CUBE}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}" ixy="0" ixz="0" iyy="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}" iyz="0" izz="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}"/>
      </inertial>
    </link>

    <joint name="joint_disc_swcube" type="revolute">
          <parent link="link_disc"/>
          <child link="link_southwestCube"/>
          <origin rpy="0 0 0" xyz="-0.0707 -0.0707 0"/>
          <limit effort="0" lower="0" upper="0" velocity="0"/>
          <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint>

    <link name="link_southwestCube">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${L_CUBE} ${L_CUBE} ${L_CUBE}" />
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${L_CUBE} ${L_CUBE} ${L_CUBE}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_CUBE}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}" ixy="0" ixz="0" iyy="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}" iyz="0" izz="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}"/>
      </inertial>
    </link>

    <joint name="joint_disc_secube" type="revolute">
          <parent link="link_disc"/>
          <child link="link_southeastCube"/>
          <origin rpy="0 0 0" xyz="0.0707 -0.0707 0"/>
          <limit effort="0" lower="0" upper="0" velocity="0"/>
          <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint>

    <link name="link_southeastCube">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${L_CUBE} ${L_CUBE} ${L_CUBE}" />
            </geometry>
            <material name="sky"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${L_CUBE} ${L_CUBE} ${L_CUBE}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${M_CUBE}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}" ixy="0" ixz="0" iyy="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}" iyz="0" izz="${1/12*M_CUBE*(L_CUBE*L_CUBE+L_CUBE*L_CUBE)}"/>
      </inertial>
    </link>



</robot>
