<?xml version="1.0" ?>

<robot name="cable_joint" xmlns:xacro="https://www.ros.org/wiki/xacro" >

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <!-- properties of link_base -->
    <xacro:property name="R_BASE" value="0.1"/>
    <xacro:property name="L_BASE" value="0.02"/>
    <xacro:property name="M_BASE" value="1000"/>
    <!-- properties of link_base -->
    <xacro:property name="R_BASE" value="0.1"/>
    <xacro:property name="L_BASE" value="0.02"/>
    <xacro:property name="M_BASE" value="1000"/>

    <xacro:property name="body_length" value="0.02" /> <!-- Size of square 'camera' box -->

    <!-- Import all Gazebo-customization elements, including Gazebo colors -->
    <xacro:include filename="$(find cable_joint_description)/urdf/cable_joint.gazebo.xacro" />
    <!-- Import Rviz colors -->
    <xacro:include filename="$(find cable_joint_description)/urdf/materials.xacro" />

    <!-- Used for fixing robot to Gazebo 'base_link' -->
    <link name="world"/>

    <!-- <joint name="joint_world_base" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="world"/>
    <child link="link_base"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint> -->

    <link name="link_base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="{L_BASE}" radius="${R_BASE}"/>
            </geometry>
        <material name="black"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${L_BASE}" radius="${R_BASE}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1000"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${1/12*M_BASE*(3*R_HAT*R_HAT+L_HAT*L_HAT)}" ixy="0" ixz="0" iyy="${1/12*M_BASE*(3*R_HAT*R_HAT+L_HAT*L_HAT)}" iyz="0" izz="${1/2*M_BASE*R_HAT*R_HAT}"/>
        </inertial>
    </link>

    <joint name="joint_world_camerabody" type="revolute">
    <origin rpy="0 0 ${PI/2}" xyz="0 -0.5 ${body_length/2}"/>
    <parent link="world"/>
    <child link="link_camera_body"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint>

  <link name="link_camera_body">
    <collision>
      <origin rpy="0 0 0" xyz="0 -0.5 0"/>
      <geometry>
        <box size="${body_length} ${body_length*2} ${body_length*2}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_length*2} ${body_length*2}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="0.1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
  </link>

  <joint name="joint_camerabody_lens" type="revolute">
    <origin rpy="0 ${PI/2} 0" xyz="${body_length/2+body_length/16} 0 0"/>
    <parent link="link_camera_body"/>
    <child link="link_lens"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

  <link name="link_lens">
    <collision>
      <origin rpy="0 0 0" xyz="0 -0.5 0"/>
      <geometry>
        <cylinder length="${body_length/8}" radius="${body_length/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${body_length/8}" radius="${body_length/2}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
  </link>

  <!-- camera needs to be rotated coreectly -->
  <joint name="camera_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-PI/2} ${-PI/2} ${PI/2}"/>
    <parent link="link_lens"/>
    <child link="link_optical"/>
  </joint>

  <link name="link_optical">
  </link>

  <joint name="joint_base_lowersupport" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <parent link="link_base"/>
    <child link="link_lower_support"/>
    <origin rpy="0 0 0" xyz="0 0 0.01"/>
  </joint>

  <link name="link_lower_support">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.07"/>
      <geometry>
        <cylinder length="0.14" radius="0.015"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.07"/>
      <geometry>
        <cylinder length="0.14" radius="0.015"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <inertial>
      <mass value="100"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <joint name="joint_base_pinwest" type="revolute">
    <parent link="link_base"/>
    <child link="link_pin_west"/>
    <origin rpy="0 0 0" xyz="-0.1 0 0.01"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

  <link name="link_pin_west">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>

  <joint name="joint_base_pineast" type="revolute">
    <parent link="link_base"/>
    <child link="link_pin_east"/>
    <origin rpy="0 0 0" xyz="0.1 0 0.01"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

  <link name="link_pin_east">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <inertial>
      <mass value="1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>

  <joint name="joint_lowersupport_ballroll" type="revolute">
    <parent link="link_lower_support"/>
    <child link="link_ball_roll"/>
    <origin rpy="0 0 0" xyz="0 0 0.14"/>
    <axis xyz="1 0 0"/>
    <limit effort="10" velocity="${PI*2}" lower="${-4*PI/9}" upper="${4*PI/9}"/>
  </joint>

  <link name="link_ball_roll">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.00001"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.00001"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <mass value="0.1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-8" ixy="0" ixz="0" iyy="1e-8" iyz="0" izz="1e-8"/>
    </inertial>
  </link>

  <joint name="joint_ballroll_ballpitch" type="revolute">
    <parent link="link_ball_roll"/>
    <child link="link_ball_pitch"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10" velocity="${PI*2}" lower="${-4*PI/9}" upper="${4*PI/9}"/>
  </joint>

  <link name="link_ball_pitch">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.00001"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.00001"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <mass value="0.1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-8" ixy="0" ixz="0" iyy="1e-8" iyz="0" izz="1e-8"/>
    </inertial>
  </link>

  <joint name="joint_ballpitch_ballyaw" type="revolute">
    <parent link="link_ball_pitch"/>
    <child link="link_ball_yaw"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" velocity="${PI*2}" lower="${-PI/8}" upper="${PI/8}"/>
  </joint>

  <link name="link_ball_yaw">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <inertial>
      <mass value="1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
  </link>

  <joint name="joint_ballyaw_uppersupport" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0.03"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis xyz="0 0 1"/>
    <parent link="link_ball_yaw"/>
    <child link="link_upper_support"/>
  </joint>

  <link name="link_upper_support">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.01"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.01"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <inertial>
      <mass value="1e-5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-8" ixy="0" ixz="0" iyy="1e-8" iyz="0" izz="1e-8"/>
    </inertial>
  </link>

  <joint name="joint_uppersupport_disc" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0.02"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis xyz="0 0 1"/>
    <parent link="link_upper_support"/>
    <child link="link_disc"/>
  </joint>

  <link name="link_disc">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.1"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <mass value="0.0001"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
  </link>

  <joint name="joint_disc_cubenortheast" type="revolute">
    <parent link="link_disc"/>
    <child link="link_cube_northeast"/>
    <origin rpy="0 0 0" xyz="0.0707 0.0707 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

  <link name="link_cube_northeast">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
      <material name="purple"/>
    </visual>
    <inertial>
      <mass value="1e-5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-8" ixy="0" ixz="0" iyy="1e-8" iyz="0" izz="1e-8"/>
    </inertial>
  </link>

  <joint name="joint_disc_cubenorthwest" type="revolute">
    <parent link="link_disc"/>
    <child link="link_cube_northwest"/>
    <origin rpy="0 0 0" xyz="-0.0707 0.0707 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

  <link name="link_cube_northwest">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="1e-5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-8" ixy="0" ixz="0" iyy="1e-8" iyz="0" izz="1e-8"/>
    </inertial>
  </link>

  <joint name="joint_disc_cubesouthwest" type="revolute">
    <parent link="link_disc"/>
    <child link="link_cube_southwest"/>
    <origin rpy="0 0 0" xyz="-0.0707 -0.0707 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

  <link name="link_cube_southwest">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <mass value="1e-5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-8" ixy="0" ixz="0" iyy="1e-8" iyz="0" izz="1e-8"/>
    </inertial>
  </link>

  <joint name="joint_disc_cubesoutheast" type="revolute">
    <parent link="link_disc"/>
    <child link="link_cube_southeast"/>
    <origin rpy="0 0 0" xyz="0.0707 -0.0707 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

  <link name="link_cube_southeast">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
      <material name="sky"/>
    </visual>
    <inertial>
      <mass value="1e-5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-8" ixy="0" ixz="0" iyy="1e-8" iyz="0" izz="1e-8"/>
    </inertial>
  </link>

</robot>
